# Generated by Django 4.2.7 on 2023-11-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='people',
            field=models.SmallIntegerField(default=4),
        ),
    ]
