# Generated by Django 4.2.7 on 2023-12-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0002_booking_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='full_name',
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
