# Generated by Django 4.2.7 on 2023-12-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0004_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
