# Generated by Django 4.2.7 on 2023-12-27 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obe', '0005_alter_menu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title_name', models.CharField(db_index=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(db_index=True, max_length=200)),
                ('price', models.FloatField()),
                ('inventory', models.SmallIntegerField()),
                ('menu_item_description', models.TextField(default='', max_length=1000)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='obe.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
